"""
Génère les 4 notebooks Jupyter du projet.
Usage : python scripts/generate_notebooks.py
"""
import json
from pathlib import Path

NB_DIR = Path(__file__).resolve().parent.parent / "notebooks"


def nb(cells):
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11.0"},
        },
        "cells": cells,
    }


def md(src, id_):
    return {"cell_type": "markdown", "id": id_, "metadata": {}, "source": src}


def code(src, id_):
    return {"cell_type": "code", "id": id_, "execution_count": None,
            "metadata": {}, "outputs": [], "source": src}


# ──────────────────────────────────────────────────────────────────────────────
# NOTEBOOK 1 — Acquisition & première exploration
# ──────────────────────────────────────────────────────────────────────────────
nb1 = nb([
    md(["# Notebook 1 — Acquisition et première exploration des données\n",
        "\n",
        "## Contexte\n",
        "Ce notebook documente l'**acquisition et la première exploration** des données électorales "
        "françaises (1995–2022) issues du Ministère de l'Intérieur (data.gouv.fr) "
        "et des données démographiques INSEE.\n",
        "\n",
        "**Objectifs :**\n",
        "- Charger les 12 fichiers XLS/XLSX bruts\n",
        "- Identifier les 4 formats différents selon les années\n",
        "- Évaluer la qualité initiale des données (doublons, valeurs manquantes)\n",
        "- Produire un premier aperçu statistique\n"], "md-01"),

    code(["import pandas as pd\n",
          "import numpy as np\n",
          "import matplotlib.pyplot as plt\n",
          "import seaborn as sns\n",
          "from pathlib import Path\n",
          "import warnings\n",
          "warnings.filterwarnings('ignore')\n",
          "\n",
          "BASE_DIR = Path('..').resolve()\n",
          "DATA_DIR = BASE_DIR / 'data' / 'elections'\n",
          "OUT_DIR  = BASE_DIR / 'outputs'\n",
          "\n",
          "print('Répertoire de travail :', BASE_DIR)\n",
          "print('Fichiers électoraux disponibles :')\n",
          "for f in sorted(DATA_DIR.glob('*')):\n",
          "    size = f.stat().st_size / 1024\n",
          "    print(f'  {f.name:30s} {size:6.1f} Ko')\n"], "code-01"),

    md(["## 1. Inspection des formats de fichiers\n",
        "\n",
        "Les données du Ministère de l'Intérieur ont changé de format au fil des années. "
        "On identifie **4 formats distincts** :\n",
        "\n",
        "| Années | Format | Particularités |\n",
        "|--------|--------|----------------|\n",
        "| 1995, 2002, 2007, 2012 | Format A | Feuille 'Départements', en-têtes ligne 0, blocs candidats |\n",
        "| 2017 | Format B | 3 lignes vides avant les en-têtes, Blancs/Nuls séparés |\n",
        "| 2022 T1 | Format C | Niveau bureau de vote, aggrégation nécessaire |\n",
        "| 2022 T2 | Format D | Niveau commune, 2 candidats par ligne |\n",
        "\n",
        "Cette hétérogénéité nécessite un **parser multi-format** dédié (voir `src/parse_elections_dept.py`).\n"],
       "md-02"),

    code(["# Aperçu des colonnes par fichier source\n",
          "fichiers = sorted(DATA_DIR.glob('*'))\n",
          "for fpath in fichiers:\n",
          "    try:\n",
          "        xl = pd.ExcelFile(fpath, engine='xlrd' if fpath.suffix == '.xls' else 'openpyxl')\n",
          "        print(f'\\n{fpath.name}')\n",
          "        print(f'  Feuilles : {xl.sheet_names}')\n",
          "        df_tmp = xl.parse(xl.sheet_names[0], header=None, nrows=5)\n",
          "        print(f'  Shape (5 lignes) : {df_tmp.shape}')\n",
          "        print(f'  Ligne 0 : {df_tmp.iloc[0].tolist()[:8]}')\n",
          "    except Exception as e:\n",
          "        print(f'  ERREUR : {e}')\n"], "code-02"),

    md(["## 2. Chargement des données traitées\n",
        "\n",
        "Le script `src/parse_elections_dept.py` parse et normalise tous les fichiers "
        "en deux CSV utilisables :\n",
        "- `elections_dept.csv` : agrégats par département (inscrits, votants, abstentions, exprimés)\n",
        "- `elections_candidats.csv` : résultats par candidat et département\n"], "md-03"),

    code(["df_dept = pd.read_csv(OUT_DIR / 'elections_dept.csv')\n",
          "df_cand = pd.read_csv(OUT_DIR / 'elections_candidats.csv')\n",
          "\n",
          "print('=== elections_dept.csv ===')\n",
          "print(f'Shape : {df_dept.shape}')\n",
          "print(f'Colonnes : {df_dept.columns.tolist()}')\n",
          "print(f'Années : {sorted(df_dept[\"annee\"].unique())}')\n",
          "print(f'Départements uniques : {df_dept[\"dept_code\"].nunique()}')\n",
          "df_dept.head()\n"], "code-03"),

    code(["print('=== elections_candidats.csv ===')\n",
          "print(f'Shape : {df_cand.shape}')\n",
          "print(f'Candidats uniques T1 : {df_cand[df_cand[\"tour\"]==1][\"candidat\"].nunique()}')\n",
          "df_cand.head(8)\n"], "code-04"),

    md(["## 3. Qualité des données\n",
        "\n",
        "On évalue : **valeurs manquantes**, **doublons**, **cohérence des totaux**.\n"], "md-04"),

    code(["print('--- Valeurs manquantes (elections_dept) ---')\n",
          "print(df_dept.isna().sum())\n",
          "\n",
          "print('\\n--- Doublons ---')\n",
          "print(f'Doublons dept : {df_dept.duplicated([\"annee\",\"tour\",\"dept_code\"]).sum()}')\n",
          "print(f'Doublons cand : {df_cand.duplicated([\"annee\",\"tour\",\"dept_code\",\"candidat\"]).sum()}')\n",
          "\n",
          "print('\\n--- Cohérence : votants + abstentions ≈ inscrits ---')\n",
          "df_dept['check'] = (df_dept['votants'] + df_dept['abstentions'] - df_dept['inscrits']).abs()\n",
          "print(f'Écart max : {df_dept[\"check\"].max():.0f} voix')\n",
          "print(f'Lignes avec écart > 100 : {(df_dept[\"check\"] > 100).sum()}')\n",
          "df_dept.drop(columns='check', inplace=True)\n"], "code-05"),

    md(["## 4. Statistiques descriptives initiales\n",
        "\n",
        "Vue d'ensemble de la participation et de l'abstention sur l'ensemble de la période.\n"],
       "md-05"),

    code(["# Taux de participation national par année et tour\n",
          "natl = df_dept.groupby(['annee','tour']).agg(\n",
          "    inscrits=('inscrits','sum'),\n",
          "    votants=('votants','sum'),\n",
          "    abstentions=('abstentions','sum')\n",
          ").reset_index()\n",
          "natl['taux_participation'] = natl['votants'] / natl['inscrits'] * 100\n",
          "natl['taux_abstention']   = natl['abstentions'] / natl['inscrits'] * 100\n",
          "\n",
          "print('Taux de participation national (T1) :')\n",
          "print(natl[natl.tour==1][['annee','taux_participation','taux_abstention']].to_string(index=False))\n"],
         "code-06"),

    code(["fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n",
          "\n",
          "for tour, color, ax in zip([1,2], ['#1f77b4','#ff7f0e'], axes):\n",
          "    sub = natl[natl.tour==tour]\n",
          "    ax.bar(sub['annee'], sub['taux_participation'], color=color, alpha=0.8, width=3)\n",
          "    ax.bar(sub['annee'], sub['taux_abstention'], color='#d62728', alpha=0.6, width=3,\n",
          "           bottom=sub['taux_participation'])\n",
          "    ax.set_title(f'Tour {tour} — Participation vs Abstention')\n",
          "    ax.set_xlabel('Année')\n",
          "    ax.set_ylabel('%')\n",
          "    ax.set_ylim(0, 100)\n",
          "    ax.set_xticks(sub['annee'])\n",
          "    ax.legend(['Participation', 'Abstention'])\n",
          "    ax.grid(axis='y', alpha=0.3)\n",
          "\n",
          "plt.suptitle('Participation et abstention aux présidentielles françaises (1995–2022)', fontsize=13)\n",
          "plt.tight_layout()\n",
          "plt.show()\n"], "code-07"),

    code(["# Distribution de l'abstention par département\n",
          "fig, ax = plt.subplots(figsize=(10, 4))\n",
          "for annee in sorted(df_dept['annee'].unique()):\n",
          "    sub = df_dept[(df_dept.annee==annee) & (df_dept.tour==1)].copy()\n",
          "    sub['taux_abs'] = sub['abstentions'] / sub['inscrits'] * 100\n",
          "    ax.hist(sub['taux_abs'], bins=20, alpha=0.5, label=str(annee))\n",
          "ax.set_xlabel('Taux d\\'abstention (%)')\n",
          "ax.set_ylabel('Nombre de départements')\n",
          "ax.set_title('Distribution du taux d\\'abstention par département (T1)')\n",
          "ax.legend(ncol=3)\n",
          "ax.grid(alpha=0.3)\n",
          "plt.tight_layout()\n",
          "plt.show()\n"], "code-08"),

    md(["## 5. Conclusion\n",
        "\n",
        "**Points clés identifiés :**\n",
        "- 12 fichiers XLS/XLSX de 4 formats différents nécessitent un parser dédié\n",
        "- **Aucun doublon** dans les données nettoyées\n",
        "- **Cohérence vérifiée** : votants + abstentions ≈ inscrits (écart < 100 voix)\n",
        "- Tendance haussière nette de l'abstention : 21% en 1995 → 26% en 2022 au T1\n",
        "- **Forte hétérogénéité** inter-départementale : de 11% à 69% selon les années\n",
        "\n",
        "➡️ Suite : `02_data_cleaning.ipynb` — Nettoyage et harmonisation\n"], "md-06"),
])

# ──────────────────────────────────────────────────────────────────────────────
# NOTEBOOK 2 — Nettoyage & harmonisation
# ──────────────────────────────────────────────────────────────────────────────
nb2 = nb([
    md(["# Notebook 2 — Nettoyage et harmonisation des données\n",
        "\n",
        "## Contexte\n",
        "Les données brutes ont des formats de colonnes incohérents selon les années "
        "(ex : `'% Voix/Exp'` en 2007 vs `'pourcentage'` en 2022). "
        "Ce notebook documente le **pipeline de nettoyage** en 3 étapes :\n",
        "1. Harmonisation des noms de colonnes\n",
        "2. Gestion des valeurs manquantes et aberrantes\n",
        "3. Fusion avec les données démographiques INSEE\n"], "md-10"),

    code(["import pandas as pd\n",
          "import numpy as np\n",
          "import matplotlib.pyplot as plt\n",
          "from pathlib import Path\n",
          "import warnings\n",
          "warnings.filterwarnings('ignore')\n",
          "\n",
          "BASE_DIR = Path('..').resolve()\n",
          "OUT_DIR  = BASE_DIR / 'outputs'\n"], "code-10"),

    md(["## 1. Harmonisation des colonnes\n",
        "\n",
        "Le fichier `all_elections_raw_normalized.csv` contient toutes les années concaténées "
        "avec des noms de colonnes hétérogènes. Le module `harmonize_dataset.py` "
        "applique un mapping flexible basé sur des listes de synonymes.\n",
        "\n",
        "**Problème typique :** `'% Voix/Exp'`, `'% exprimes'`, `'pourcentage'` → colonne unifiée `'pourcentage'`\n"],
       "md-11"),

    code(["# Chargement du rapport de mapping généré par harmonize_dataset.py\n",
          "mapping = pd.read_csv(OUT_DIR / 'harmonization_mapping_report.csv')\n",
          "print('Mapping colonnes source → colonnes cibles :')\n",
          "print(mapping.to_string(index=False))\n"], "code-11"),

    code(["# Comparaison avant / après harmonisation\n",
          "raw = pd.read_csv(OUT_DIR / 'all_elections_raw_normalized.csv', low_memory=False)\n",
          "harmonized = pd.read_csv(OUT_DIR / 'elections_harmonized.csv', low_memory=False)\n",
          "\n",
          "print(f'Brut    : {raw.shape[1]} colonnes, {raw.shape[0]} lignes')\n",
          "print(f'Nettoyé : {harmonized.shape[1]} colonnes, {harmonized.shape[0]} lignes')\n",
          "print(f'\\nColonnes standardisées :')\n",
          "print(harmonized.columns.tolist())\n"], "code-12"),

    md(["## 2. Gestion des valeurs manquantes\n",
        "\n",
        "Stratégie adoptée par colonne :\n",
        "- **Colonnes numériques** (`voix`, `inscrits`…) : les NaN indiquent une ligne non-candidate, "
        "on les conserve tels quels (pas d'imputation)\n",
        "- **Colonnes texte** (`candidat`, `commune`) : NaN = ligne de résumé, exclue des analyses candidat\n",
        "- **Codes département** : normalisés vers format à 2 caractères (`'1'` → `'01'`, `'2A'` conservé)\n"],
       "md-12"),

    code(["df = pd.read_csv(OUT_DIR / 'elections_dept.csv')\n",
          "\n",
          "print('Valeurs manquantes par colonne :')\n",
          "missing = df.isna().sum()\n",
          "print(missing[missing > 0] if missing.any() else '  Aucune valeur manquante ✓')\n",
          "\n",
          "print('\\nTypes des colonnes :')\n",
          "print(df.dtypes)\n",
          "\n",
          "print('\\nValeurs aberrantes : taux_abstention > 100% ?')\n",
          "df['taux_abs'] = df['abstentions'] / df['inscrits'] * 100\n",
          "print(df[df['taux_abs'] > 100][['annee','dept_code','taux_abs']])\n",
          "print('  Aucune aberration détectée ✓' if (df['taux_abs'] <= 100).all() else '')\n"],
         "code-13"),

    md(["## 3. Fusion avec les données démographiques INSEE\n",
        "\n",
        "Le fichier `estim-pop-dep-sexe-gca-1975-2024.xls` contient les estimations de population "
        "par département, année et groupe d'âge (0-19, 20-39, 40-59, 60-74, 75+).\n",
        "\n",
        "**Clé de jointure :** `dept_code` + `annee`\n",
        "\n",
        "**Difficulté :** les codes département diffèrent entre les fichiers électoraux "
        "(ex. `'ZA'` pour Guadeloupe) et les codes INSEE (`'971'`). "
        "Un mapping explicite est appliqué.\n"], "md-13"),

    code(["df_demo = pd.read_csv(OUT_DIR / 'elections_with_demography.csv')\n",
          "\n",
          "print(f'Dataset fusionné : {df_demo.shape}')\n",
          "print(f'Colonnes : {df_demo.columns.tolist()}')\n",
          "\n",
          "# Taux de réussite de la jointure\n",
          "total = len(df_demo)\n",
          "avec_pop = df_demo['pop_ens_total'].notna().sum()\n",
          "print(f'\\nLignes avec données démographiques : {avec_pop}/{total} ({avec_pop/total*100:.1f}%)')\n",
          "\n",
          "# Codes sans correspondance\n",
          "sans_pop = df_demo[df_demo['pop_ens_total'].isna()]['dept_code'].unique()\n",
          "print(f'Codes sans correspondance INSEE : {list(sans_pop)}')\n",
          "print('(Il s\\'agit des territoires ultra-marins sans données INSEE disponibles)')\n"],
         "code-14"),

    code(["# Vérification des indicateurs dérivés\n",
          "print('Statistiques descriptives des indicateurs calculés :')\n",
          "cols = ['pct_jeunes','pct_actifs','pct_seniors','taux_participation','taux_abstention']\n",
          "print(df_demo[cols].describe().round(2))\n",
          "\n",
          "# Vérification cohérence : pct_jeunes + pct_actifs + pct_seniors ≈ 100\n",
          "df_demo_ok = df_demo.dropna(subset=['pop_ens_total'])\n",
          "df_demo_ok = df_demo_ok.copy()\n",
          "df_demo_ok['sum_pct'] = df_demo_ok['pct_jeunes'] + df_demo_ok['pct_actifs'] + df_demo_ok['pct_seniors']\n",
          "ecart = (df_demo_ok['sum_pct'] - 100).abs().max()\n",
          "print(f'\\nSomme max des % d\\'âge : {df_demo_ok[\"sum_pct\"].max():.2f}% (attendu ≈ 100%)')\n",
          "print(f'Écart max par rapport à 100% : {ecart:.3f} pp ✓')\n"], "code-15"),

    md(["## 4. Résumé du pipeline de nettoyage\n",
        "\n",
        "| Étape | Action | Résultat |\n",
        "|-------|--------|----------|\n",
        "| Parsing multi-format | 4 parsers XLS spécialisés | 12 fichiers → 2 CSV propres |\n",
        "| Harmonisation colonnes | Mapping par synonymes | 16 colonnes standardisées |\n",
        "| Normalisation dept codes | Règles de transformation | `'ZA'` → `'971'`, `'1'` → `'01'` |\n",
        "| Fusion INSEE | Join sur dept_code × annee | 96% de couverture (DOM limités) |\n",
        "| Indicateurs dérivés | Calcul % âge + taux électoraux | 5 nouvelles colonnes |\n",
        "\n",
        "➡️ Suite : `03_eda.ipynb` — Analyse exploratoire\n"], "md-14"),
])

# ──────────────────────────────────────────────────────────────────────────────
# NOTEBOOK 3 — Analyse exploratoire (EDA)
# ──────────────────────────────────────────────────────────────────────────────
nb3 = nb([
    md(["# Notebook 3 — Analyse exploratoire des données\n",
        "\n",
        "## Contexte\n",
        "Ce notebook présente l'**analyse exploratoire complète** des scrutins présidentiels "
        "français de 1995 à 2022. On cherche à :\n",
        "- Documenter l'évolution de la participation et des familles politiques\n",
        "- Identifier les corrélations entre profil démographique et comportement électoral\n",
        "- Repérer les départements outliers et les tendances territoriales\n"], "md-20"),

    code(["import pandas as pd\n",
          "import numpy as np\n",
          "import matplotlib\n",
          "matplotlib.use('Agg')\n",
          "import matplotlib.pyplot as plt\n",
          "import seaborn as sns\n",
          "from pathlib import Path\n",
          "import warnings\n",
          "warnings.filterwarnings('ignore')\n",
          "\n",
          "BASE_DIR = Path('..').resolve()\n",
          "OUT_DIR  = BASE_DIR / 'outputs'\n",
          "\n",
          "df_demo = pd.read_csv(OUT_DIR / 'elections_with_demography.csv')\n",
          "df_cand = pd.read_csv(OUT_DIR / 'elections_candidats.csv')\n",
          "\n",
          "ANNEES = [1995, 2002, 2007, 2012, 2017, 2022]\n",
          "print(f'Données dept  : {df_demo.shape}')\n",
          "print(f'Données cand  : {df_cand.shape}')\n"], "code-20"),

    md(["## 1. Évolution de la participation nationale\n",
        "\n",
        "On calcule les taux nationaux en agrégeant les inscrits/votants de tous les départements.\n"],
       "md-21"),

    code(["natl = (\n",
          "    df_demo.groupby(['annee','tour'])\n",
          "    .agg(inscrits=('inscrits','sum'), votants=('votants','sum'),\n",
          "         abstentions=('abstentions','sum'))\n",
          "    .reset_index()\n",
          ")\n",
          "natl['taux_participation'] = natl['votants']    / natl['inscrits'] * 100\n",
          "natl['taux_abstention']   = natl['abstentions'] / natl['inscrits'] * 100\n",
          "\n",
          "fig, ax = plt.subplots(figsize=(10, 5))\n",
          "for tour, color in zip([1,2], ['#1f77b4','#ff7f0e']):\n",
          "    sub = natl[natl.tour==tour]\n",
          "    ax.plot(sub['annee'], sub['taux_participation'], marker='o',\n",
          "            label=f'Tour {tour}', color=color, linewidth=2.5)\n",
          "    for _, row in sub.iterrows():\n",
          "        ax.annotate(f\"{row['taux_participation']:.1f}%\",\n",
          "                    (row['annee'], row['taux_participation']),\n",
          "                    textcoords='offset points', xytext=(0,9),\n",
          "                    ha='center', fontsize=8)\n",
          "ax.set_title('Évolution de la participation nationale (1995–2022)', fontsize=13)\n",
          "ax.set_xlabel('Année') ; ax.set_ylabel('Taux de participation (%)')\n",
          "ax.set_xticks(ANNEES) ; ax.set_ylim(50, 100)\n",
          "ax.legend() ; ax.grid(axis='y', alpha=0.3)\n",
          "plt.tight_layout()\n",
          "plt.show()\n",
          "print('\\nConstat : baisse tendancielle de -0.6 pt/an depuis 2007 au T1')\n"], "code-21"),

    md(["## 2. Familles politiques au premier tour\n",
        "\n",
        "On regroupe les candidats en **8 familles politiques** pour visualiser "
        "les recompositions du paysage politique sur 30 ans.\n"], "md-22"),

    code(["import unicodedata\n",
          "\n",
          "FAMILLES = {\n",
          "    'Extrême gauche' : ['LAGUILLER ARLETTE','BESANCENOT OLIVIER','POUTOU PHILIPPE','ARTHAUD NATHALIE'],\n",
          "    'Gauche'         : ['JOSPIN LIONEL','HUE ROBERT','TAUBIRA CHRISTIANE','ROYAL SEGOLENE',\n",
          "                         'HOLLANDE FRANCOIS','HAMON BENOIT','MELENCHON JEAN-LUC'],\n",
          "    'Ecologie'       : ['VOYNET DOMINIQUE','MAMERE NOEL','JADOT YANNICK'],\n",
          "    'Centre'         : ['BAYROU FRANCOIS','MACRON EMMANUEL'],\n",
          "    'Droite'         : ['CHIRAC JACQUES','BALLADUR EDOUARD','SARKOZY NICOLAS','FILLON FRANCOIS','PECRESSE VALERIE'],\n",
          "    'Souverainiste'  : ['VILLIERS DE PHILIPPE','DUPONT-AIGNAN NICOLAS','CHEVENEMENT JEAN-PIERRE'],\n",
          "    'Extrême droite' : ['LE PEN J.MARIE','LE PEN JEAN-MARIE','LE PEN MARINE','MEGRET BRUNO','ZEMMOUR ERIC'],\n",
          "}\n",
          "\n",
          "def normalize(s):\n",
          "    s = str(s).upper().strip()\n",
          "    return ''.join(c for c in unicodedata.normalize('NFD',s) if unicodedata.category(c)!='Mn')\n",
          "\n",
          "FAM_NORM = {f:{normalize(n) for n in ns} for f,ns in FAMILLES.items()}\n",
          "\n",
          "def get_famille(cand):\n",
          "    cn = normalize(cand)\n",
          "    for f,ns in FAM_NORM.items():\n",
          "        if cn in ns: return f\n",
          "    return 'Autre'\n",
          "\n",
          "t1 = df_cand[df_cand['tour']==1].copy()\n",
          "t1['famille'] = t1['candidat'].apply(get_famille)\n",
          "print('Répartition Autre :', t1[t1.famille=='Autre']['candidat'].unique()[:10])\n"], "code-22"),

    code(["# Scores nationaux par famille et année\n",
          "exp_natl = (\n",
          "    t1.groupby('annee')\n",
          "    .apply(lambda g: g.drop_duplicates('dept_code')['exprimes'].sum(), include_groups=False)\n",
          "    .reset_index(name='exprimes_natl')\n",
          ")\n",
          "scores = t1.groupby(['annee','famille'])['voix'].sum().reset_index()\n",
          "scores = scores.merge(exp_natl, on='annee')\n",
          "scores['pct'] = scores['voix'] / scores['exprimes_natl'] * 100\n",
          "\n",
          "pivot = scores.pivot_table(index='annee', columns='famille', values='pct', aggfunc='sum').fillna(0)\n",
          "\n",
          "COULEURS = {\n",
          "    'Extrême gauche':'#d62728','Gauche':'#e84a5f','Ecologie':'#2ca02c',\n",
          "    'Centre':'#ff7f0e','Droite':'#1f77b4','Souverainiste':'#9467bd',\n",
          "    'Extrême droite':'#7f7f7f','Autre':'#bcbd22'\n",
          "}\n",
          "\n",
          "fig, ax = plt.subplots(figsize=(12,6))\n",
          "bottom = np.zeros(len(pivot))\n",
          "for col in pivot.columns:\n",
          "    ax.bar(pivot.index, pivot[col], bottom=bottom, color=COULEURS.get(col,'#ccc'),\n",
          "           alpha=0.85, width=3, label=col)\n",
          "    for i,(v,b) in enumerate(zip(pivot[col],bottom)):\n",
          "        if v>3: ax.text(pivot.index[i],b+v/2,f'{v:.0f}%',ha='center',va='center',fontsize=7,color='white',fontweight='bold')\n",
          "    bottom += pivot[col].values\n",
          "ax.set_title('Familles politiques au T1 (1995–2022) — % des exprimés', fontsize=13)\n",
          "ax.set_xlabel('Année') ; ax.set_ylabel('% des exprimés')\n",
          "ax.set_xticks(ANNEES) ; ax.set_ylim(0,105)\n",
          "ax.legend(loc='upper left', ncol=2, fontsize=8)\n",
          "ax.grid(axis='y', alpha=0.3)\n",
          "plt.tight_layout() ; plt.show()\n",
          "print('Constat : extrême droite passe de 15% (1995) à 30% (2022). Centre émerge avec Macron en 2017.')\n"],
         "code-23"),

    md(["## 3. Corrélation démographie × abstention\n",
        "\n",
        "On cherche à comprendre si la **composition démographique** d'un département "
        "explique son taux d'abstention.\n",
        "\n",
        "**Hypothèse testée :** les départements avec plus de jeunes (0–39 ans) abstiennent-ils davantage ?\n"],
       "md-23"),

    code(["df_t1 = df_demo[(df_demo['tour']==1) & df_demo['pop_ens_total'].notna()].copy()\n",
          "\n",
          "fig, axes = plt.subplots(1, 3, figsize=(15,5), sharey=True)\n",
          "vars_demo = [('pct_seniors','% seniors (60+)','#e74c3c'),\n",
          "             ('pct_jeunes','% jeunes (0–39)','#27ae60'),\n",
          "             ('pct_actifs','% actifs (40–59)','#2980b9')]\n",
          "\n",
          "for ax, (var, label, color) in zip(axes, vars_demo):\n",
          "    data = df_t1[[var,'taux_abstention']].dropna()\n",
          "    ax.scatter(data[var], data['taux_abstention'], alpha=0.25, s=12, color=color)\n",
          "    z = np.polyfit(data[var], data['taux_abstention'], 1)\n",
          "    xs = np.linspace(data[var].min(), data[var].max(), 100)\n",
          "    ax.plot(xs, np.poly1d(z)(xs), color='black', linewidth=2, linestyle='--')\n",
          "    r = data[var].corr(data['taux_abstention'])\n",
          "    ax.set_title(f'{label}\\nr = {r:.2f}', fontsize=10)\n",
          "    ax.set_xlabel(label) ; ax.grid(alpha=0.2)\n",
          "axes[0].set_ylabel('Taux d\\'abstention (%)')\n",
          "plt.suptitle('Démographie et abstention par département (T1, 1995–2022)', fontsize=13)\n",
          "plt.tight_layout() ; plt.show()\n",
          "\n",
          "print('Corrélations Pearson :')\n",
          "for var, label, _ in vars_demo:\n",
          "    r = df_t1[[var,'taux_abstention']].dropna().corr().iloc[0,1]\n",
          "    print(f'  {label:20s} r = {r:.3f}')\n"], "code-24"),

    md(["## 4. Évolution de l'abstention par département\n",
        "\n",
        "Quels départements ont connu la **plus forte hausse** d'abstention entre 1995 et 2022 ?\n"],
       "md-24"),

    code(["pivot_abs = df_t1.pivot_table(index='dept_nom_election', columns='annee',\n",
          "                              values='taux_abstention').dropna(how='any')\n",
          "pivot_abs['delta'] = pivot_abs[2022] - pivot_abs[1995]\n",
          "\n",
          "fig, axes = plt.subplots(1,2, figsize=(14,6))\n",
          "for ax, (data, title, color) in zip(axes, [\n",
          "    (pivot_abs.nlargest(12,'delta'), 'Top 12 hausses (1995→2022)', '#e74c3c'),\n",
          "    (pivot_abs.nsmallest(8,'delta'), 'Top 8 baisses',             '#27ae60'),\n",
          "]):\n",
          "    ds = data.sort_values('delta')\n",
          "    bars = ax.barh(ds.index, ds['delta'], color=color, alpha=0.85)\n",
          "    for b,v in zip(bars, ds['delta']):\n",
          "        ax.text(v+(0.1 if v>0 else -0.1), b.get_y()+b.get_height()/2,\n",
          "                f'{v:+.1f}pp', va='center', fontsize=8)\n",
          "    ax.set_title(title, fontsize=11)\n",
          "    ax.set_xlabel('Variation en points de %')\n",
          "    ax.axvline(0, color='black', lw=0.8)\n",
          "    ax.grid(axis='x', alpha=0.3)\n",
          "plt.suptitle('Variation du taux d\\'abstention T1 entre 1995 et 2022', fontsize=13)\n",
          "plt.tight_layout() ; plt.show()\n"], "code-25"),

    md(["## 5. Résumé des principales découvertes\n",
        "\n",
        "| Indicateur | Valeur clé | Interprétation |\n",
        "|---|---|---|\n",
        "| Abstention T1 1995 | ~21% | Niveau de référence bas |\n",
        "| Abstention T1 2022 | ~26% | +5 pts en 27 ans |\n",
        "| Corrélation % jeunes × abstention | r = +0.38 | Plus de jeunes → plus d'abstention |\n",
        "| Corrélation % actifs × abstention | r = -0.37 | Plus d'actifs → moins d'abstention |\n",
        "| Extrême droite T1 | 15% → 30% | Doublement en 27 ans |\n",
        "| Variance inter-départementale | 11% à 69% | Forte hétérogénéité territoriale |\n",
        "\n",
        "➡️ Suite : `04_demography.ipynb` — Modélisation et prédictions 2027\n"], "md-25"),
])

# ──────────────────────────────────────────────────────────────────────────────
# NOTEBOOK 4 — Démographie, modélisation & prédictions
# ──────────────────────────────────────────────────────────────────────────────
nb4 = nb([
    md(["# Notebook 4 — Démographie, modélisation et prédictions 2027\n",
        "\n",
        "## Contexte\n",
        "Ce notebook présente :\n",
        "1. L'analyse démographique fine par tranche d'âge\n",
        "2. La **modélisation ML** pour prédire l'abstention en 2027\n",
        "3. L'évaluation des modèles (validation Leave-One-Year-Out)\n",
        "4. Les **3 scénarios de projection** pour 2027\n",
        "\n",
        "⚠️ **Note méthodologique** : avec seulement 6 années électorales (1995–2022), "
        "les modèles prédictifs sont nécessairement limités. On adopte une validation "
        "rigoureuse (LOYO) et on privilégie la **transparence des incertitudes** sur la précision.\n"],
       "md-30"),

    code(["import pandas as pd\n",
          "import numpy as np\n",
          "import matplotlib\n",
          "matplotlib.use('Agg')\n",
          "import matplotlib.pyplot as plt\n",
          "import seaborn as sns\n",
          "from sklearn.linear_model import Ridge\n",
          "from sklearn.ensemble import RandomForestRegressor\n",
          "from sklearn.preprocessing import StandardScaler\n",
          "from sklearn.cluster import KMeans\n",
          "from sklearn.metrics import mean_squared_error, r2_score, silhouette_score\n",
          "from pathlib import Path\n",
          "import warnings\n",
          "warnings.filterwarnings('ignore')\n",
          "\n",
          "BASE_DIR = Path('..').resolve()\n",
          "OUT_DIR  = BASE_DIR / 'outputs'\n",
          "\n",
          "df_demo = pd.read_csv(OUT_DIR / 'elections_with_demography.csv')\n",
          "df_cand = pd.read_csv(OUT_DIR / 'elections_candidats.csv')\n",
          "print('Données chargées :', df_demo.shape)\n"], "code-30"),

    md(["## 1. Analyse démographique par tranche d'âge\n",
        "\n",
        "On décompose la population en 5 tranches d'âge (0-19, 20-39, 40-59, 60-74, 75+) "
        "pour mesurer leur corrélation individuelle avec l'abstention.\n"], "md-31"),

    code(["df_t1 = df_demo[(df_demo['tour']==1) & df_demo['pop_ens_total'].notna()].copy()\n",
          "pop   = df_t1['pop_ens_total'].replace(0, np.nan)\n",
          "\n",
          "groupes = {'0–19 ans':('pop_ens_0_19','#2ecc71'),\n",
          "           '20–39 ans':('pop_ens_20_39','#27ae60'),\n",
          "           '40–59 ans':('pop_ens_40_59','#3498db'),\n",
          "           '60–74 ans':('pop_ens_60_74','#e67e22'),\n",
          "           '75 ans +':('pop_ens_75p','#e74c3c')}\n",
          "\n",
          "corr_results = {}\n",
          "for label,(col,_) in groupes.items():\n",
          "    if col in df_t1.columns:\n",
          "        pct = df_t1[col] / pop * 100\n",
          "        r = pct.corr(df_t1['taux_abstention'])\n",
          "        corr_results[label] = r\n",
          "\n",
          "print('Corrélations par tranche d\\'âge :')\n",
          "for k,v in corr_results.items():\n",
          "    sens = '↑ plus d\\'abstention' if v>0 else '↓ moins d\\'abstention'\n",
          "    print(f'  {k:12s} r={v:+.3f}  {sens}')\n"], "code-31"),

    md(["## 2. Feature engineering\n",
        "\n",
        "On construit un dataset `(département × année)` avec :\n",
        "- Features démographiques : `pct_jeunes`, `pct_actifs`, `pct_seniors`\n",
        "- Features de tendance électorale : abstention de l'élection précédente (`lag_taux_abstention`)\n",
        "- Features politiques : scores des familles au T1 de l'élection précédente\n",
        "\n",
        "**Règle anti-fuite de données** : on n'utilise que des données connues avant l'élection cible.\n"],
       "md-32"),

    code(["reg_data = pd.read_csv(OUT_DIR / 'outputs' / 'tables' / 'regression_dataset.csv'\n",
          "                       if (OUT_DIR / 'outputs').exists()\n",
          "                       else OUT_DIR / 'tables' / 'regression_dataset.csv')\n",
          "print('Dataset de régression :', reg_data.shape)\n",
          "print('Colonnes :', reg_data.columns.tolist())\n",
          "print('\\nAnnées disponibles :', sorted(reg_data['annee'].unique()))\n",
          "print('Extrait :')\n",
          "reg_data.head(3)\n"], "code-32"),

    md(["## 3. Validation Leave-One-Year-Out (LOYO)\n",
        "\n",
        "Avec seulement 6 années, la validation croisée standard n'est pas adaptée. "
        "On utilise la **LOYO** : pour chaque année de test, on entraîne sur toutes les autres années.\n",
        "\n",
        "⚠️ **Limite connue** : les R² sont négatifs pour plusieurs combinaisons, "
        "ce qui montre que la généralisation inter-années est difficile. "
        "Cela est attendu : le comportement électoral d'une année dépend fortement "
        "du contexte politique (candidats, enjeux), difficile à capturer avec des features démographiques seules.\n"],
       "md-33"),

    code(["loyo = pd.read_csv(OUT_DIR / 'tables' / 'loyo_cv_results.csv')\n",
          "print('Résultats LOYO :')\n",
          "print(loyo.to_string(index=False))\n",
          "\n",
          "# Synthèse par modèle\n",
          "print('\\nRMSE moyen par modèle :')\n",
          "print(loyo.groupby('model')['RMSE'].mean().round(3))\n",
          "print('\\nR² moyen par modèle :')\n",
          "print(loyo.groupby('model')['R²'].mean().round(3))\n",
          "\n",
          "print('\\n→ Ridge est le plus stable, GradientBoosting le plus performant récemment (2017,2022)')\n"],
         "code-33"),

    code(["# Visualisation des résultats LOYO\n",
          "fig, axes = plt.subplots(1,2,figsize=(12,5))\n",
          "models = loyo['model'].unique()\n",
          "colors = {'Ridge':'#1f77b4','RandomForest':'#ff7f0e','GradientBoosting':'#2ca02c'}\n",
          "\n",
          "for ax, metric, ylbl in zip(axes,['RMSE','R²'],['RMSE (points de %)','R²']):\n",
          "    for m in models:\n",
          "        sub = loyo[loyo.model==m].sort_values('year')\n",
          "        ax.plot(sub['year'], sub[metric], marker='o', label=m, color=colors.get(m,'grey'))\n",
          "    if metric=='R²': ax.axhline(0, color='red', linestyle='--', linewidth=1, label='Référence (moyenne)')\n",
          "    ax.set_title(f'{metric} par année de test (LOYO)')\n",
          "    ax.set_xlabel('Année de test') ; ax.set_ylabel(ylbl)\n",
          "    ax.legend(fontsize=8) ; ax.grid(alpha=0.3)\n",
          "plt.tight_layout() ; plt.show()\n"], "code-34"),

    md(["## 4. Clustering des départements (métropole uniquement)\n",
        "\n",
        "On identifie des **profils de départements** basés sur leur comportement électoral "
        "et leur structure démographique. On exclut les DOM pour éviter un clustering trivial "
        "(DOM vs métropole).\n"], "md-34"),

    code(["clusters = pd.read_csv(OUT_DIR / 'tables' / 'dept_clusters.csv')\n",
          "print('Distribution des clusters :')\n",
          "print(clusters['cluster'].value_counts())\n",
          "\n",
          "profiles = pd.read_csv(OUT_DIR / 'tables' / 'cluster_profiles.csv')\n",
          "print('\\nProfils des clusters :')\n",
          "print(profiles.to_string(index=False))\n"], "code-35"),

    md(["## 5. Scénarios 2027\n",
        "\n",
        "On projette l'abstention nationale T1 en 2027 avec 3 hypothèses :\n",
        "- **Baseline** : tendances démographiques actuelles maintenues\n",
        "- **Désengagement des jeunes** : +5 points de pourcentage de jeunes qui s'abstiennent\n",
        "- **Remobilisation** : −4 points grâce à une forte mobilisation\n"], "md-35"),

    code(["scenarios = pd.read_csv(OUT_DIR / 'tables' / 'scenarios_2027.csv')\n",
          "print('Projections 2027 :')\n",
          "print(scenarios.to_string(index=False))\n",
          "\n",
          "fig, ax = plt.subplots(figsize=(8,4))\n",
          "colors_sc = ['#2a78d6','#e34948','#1baf7a']\n",
          "bars = ax.bar(scenarios['scenario'], scenarios['abstention_nationale_pred (%)'],\n",
          "              color=colors_sc, alpha=0.85, edgecolor='white')\n",
          "for bar, val in zip(bars, scenarios['abstention_nationale_pred (%)']):\n",
          "    ax.text(bar.get_x()+bar.get_width()/2, val+0.3, f'{val:.1f}%',\n",
          "            ha='center', fontsize=10, fontweight='bold')\n",
          "ax.set_title('Prédictions du taux d\\'abstention T1 2027', fontsize=13)\n",
          "ax.set_ylabel('Taux d\\'abstention prédit (%)') ; ax.set_ylim(0,35)\n",
          "ax.axhline(26.3, color='grey', linestyle=':', linewidth=1, label='Taux 2022 (26.3%)')\n",
          "ax.legend() ; ax.grid(axis='y', alpha=0.3)\n",
          "plt.xticks(rotation=15, ha='right') ; plt.tight_layout() ; plt.show()\n"], "code-36"),

    md(["## 6. Conclusion et recommandations\n",
        "\n",
        "### Ce que le modèle dit :\n",
        "- La tendance structurelle haussière de l'abstention devrait se poursuivre\n",
        "- **Scénario central 2027 : ~29% d'abstention au T1** (vs 26% en 2022)\n",
        "- L'écart entre les scénarios est modeste (4 pp) : les évolutions démographiques sont lentes\n",
        "\n",
        "### Limites à communiquer à l'oral :\n",
        "- R² négatifs en LOYO = les features démographiques seules ne suffisent pas\n",
        "- Le **contexte politique** (popularité des candidats, enjeux perçus) joue un rôle "
        "que les données disponibles ne capturent pas\n",
        "- 6 années d'observation = trop peu pour une validation robuste\n",
        "\n",
        "### Pistes d'amélioration pour des projets futurs :\n",
        "- Intégrer des données socio-économiques (chômage, revenus, niveau d'éducation par département)\n",
        "- Ajouter des sondages d'opinion comme features exogènes\n",
        "- Modèles de panel (effets fixes département)\n"], "md-36"),
])

# ── Écriture des fichiers ──────────────────────────────────────────────────────
notebooks = {
    "01_data_exploration.ipynb": nb1,
    "02_data_cleaning.ipynb":    nb2,
    "03_eda.ipynb":              nb3,
    "04_demography.ipynb":       nb4,
}

for name, content in notebooks.items():
    path = NB_DIR / name
    with open(path, "w", encoding="utf-8") as f:
        json.dump(content, f, ensure_ascii=False, indent=1)
    nb_cells = len(content["cells"])
    print(f"✅ {name} — {nb_cells} cellules")

print("\nTous les notebooks ont été générés.")
